# SITE CONFIGURATION
baseurl: "/" # set it to "/" if use for personal site. The subpath of your site, e.g. /blog/
baseurl: "" # the subpath of your site, e.g. /blog/
domain: "http://blog.kter.jp"
url: "http://blog.kter.jp" # the base hostname & protocol for your site
imageurl: "https://source.unsplash.com/category/nature/2600x500" #"https://unsplash.it/2600/500?random"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: ことえりブログ
  #avatar: avatar.png
  hometitle: Home #display on navigation menu.
  yoursitetitle: ことえりブログ
  gravatar: # Email MD5 hash
  description: "used by search engines" # used by search engines
  visiblewords: 500
  # Header and footer text
  header_text: >
     

  header_text_feature_image: img/sample_feature_img.png
  place_holder_image: img/sample_feature_img.png
  footer_text: >
   <a href="http://blog.kter.jp/">ことえりブログ</a> 

  # Icons
  rss: false
  email_address: "me at kter.jp" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "kter"
  weibo: 
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest: 
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "kter"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-47788961-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: kter
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  #str_next: "Next"
  #str_prev: "Prev"
  str_continue_reading: "Continue Reading..."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: false

# PAGINATION
enforce_ssl: "fengzhichu.com"
paginate: 5
paginate_path: "blog/page:num"
permalink: blog/:title/  #Delete preurl 'fengzhichu-theme/' if used for your personal site.

# Posted in ... with ...
sechby: 
  category:   #in
  tag:   #with

# BUILD SETTINGS
markdown: redcarpet
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

exclude: [vendor, 's3_website']

